default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: insterview_development

test:
  <<: *default
  database: insterview_test

production:
  <<: *default
  database: insterview_production
  username: insterview
  password: <%= ENV['INSTERVIEW_DATABASE_PASSWORD'] %>
